# Generated by Django 4.0.4 on 2022-05-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailinventory', '0002_pageblock_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
