name: test

on: [pull_request, push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox -e lint
        run: tox
        env:
          TOXENV: lint

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ['3.8', '3.11']
        django: ['3.2', '4.2']
        wagtail: ['4.1', '5.2', '6.0']
        exclude:
          - django: '3.2'
            wagtail: '6.0'
          - django: '4.2'
            wagtail: '4.1'
          - python: '3.11'
            django: '3.2'
        include:
          - python: '3.11'
            django: '5.0'
            wagtail: '6.0'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coveralls

      - name: Run tox
        run: |
            tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}

      - name: Store test coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: .coverage.*

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Retrieve test coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage

      - name: Check coverage
        run: tox -e coverage
