name: test

on: [pull_request, push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox -e lint
        run: tox
        env:
          TOXENV: lint

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ['3.8', '3.10']
        django: ['3.2']
        wagtail: ['2.15','3.0','4.0']
        include:
          - python: '3.8'
            django: '4.0'
            wagtail: '3.0'
          - python: '3.10'
            django: '4.0'
            wagtail: '3.0'
          - python: '3.8'
            django: '4.0'
            wagtail: '4.0'
          - python: '3.10'
            django: '4.0'
            wagtail: '4.0'
          - python: '3.8'
            django: '4.1'
            wagtail: '4.0'
          - python: '3.10'
            django: '4.1'
            wagtail: '4.0'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coveralls

      - name: Run tox
        run: |
            tox
            coveralls
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
